Extended the configure scripts
Introduced options:
-meego (+some deps)
-symbian
-config <config> (qmake config)
-make <part> (examples/tests)
-nomake <part> (examples/tests)
-help

Merge-request: 334
Reviewed-by: Oswald Buddenhagen <oswald.buddenhagen@nokia.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -29,21 +29,236 @@ BUILD_TREE=`/bin/pwd`
 SOURCE_TREE=`dirname $0`
 SOURCE_TREE=`cd "$SOURCE_TREE"; /bin/pwd`
 
+BUILD_MEEGO_STYLE=no
+BUILD_SYMBIAN_STYLE=no
+BUILD_MX_STYLE=no
+BUILD_EXAMPLES=yes
+BUILD_TESTS=yes
+HAVE_MEEGOTOUCH=no
+HAVE_XDAMAGE=no
+HAVE_CONTEXTSUBSCRIBER=no
+HAVE_MEEGOGRAPHICSSYSTEM=no
+QMAKE_CONFIG=
+OPT_HELP=no
+
 QMAKE=`which qmake` 2> /dev/null
-if [ -z $QMAKE ] && [ -n "$QTDIR" ]; then
+if [ ! -f "$QMAKE" ]; then
     QMAKE=$QTDIR/bin/qmake
+    if [ ! -f $QMAKE ]; then
+        echo "ERROR: Unable to find qmake. Try QTDIR=/path/to/qt $0."
+        exit 1
+    fi
 fi
 
 QMAKE_CACHE=$BUILD_TREE/.qmake.cache
 [ -f $QMAKE_CACHE ] && rm -f $QMAKE_CACHE
 
+# Test for pkg-config enabled dependencies
+which pkg-config > /dev/null
+if [ $? -eq 0 ]; then
+    pkg-config --exists meegotouch && HAVE_MEEGOTOUCH=yes
+    pkg-config --atleast-version=0.5.25 contextsubscriber-1.0 && HAVE_CONTEXTSUBSCRIBER=yes
+    pkg-config --exists xdamage && HAVE_XDAMAGE=yes
+fi
+
+#-------------------------------------------------------------------------------
+# parse command line arguments
+#-------------------------------------------------------------------------------
+
+# parse the arguments, setting things to "yes" or "no"
+while [ "$#" -gt 0 ]; do
+    CURRENT_OPT="$1"
+    UNKNOWN_ARG=no
+    case "$1" in
+    #Qt style no options
+    -no-*)
+        VAR=`echo $1 | sed 's,^-no-\(.*\),\1,'`
+        VAL=no
+        ;;
+    #Qt style yes options
+    -meego|-symbian|-mx|-meegotouch|-contextsubscriber|-xdamage|-meegographicssystem)
+        VAR=`echo $1 | sed 's,^-\(.*\),\1,'`
+        VAL=yes
+        ;;
+
+    -*)
+        VAR=`echo $1 | sed 's,^-\(.*\),\1,'`
+        VAL=unknown
+        ;;
+    *)
+        UNKNOWN_ARG=yes
+        ;;
+    esac
+    if [ "$UNKNOWN_ARG" = "yes" ]; then
+        echo "$1: unknown argument"
+        OPT_HELP=yes
+        ERROR=yes
+        shift
+        continue
+    fi
+    shift
+
+    UNKNOWN_OPT=no
+    case "$VAR" in
+    meego)
+        BUILD_MEEGO_STYLE=yes
+        ;;
+    symbian)
+        BUILD_SYMBIAN_STYLE=yes
+        ;;
+    mx)
+        BUILD_MX_STYLE=yes
+        ;;
+    nomake)
+        case "$1" in
+        examples)
+            BUILD_EXAMPLES=no
+            shift
+            ;;
+        tests)
+            BUILD_TESTS=no
+            shift
+            ;;
+        *)
+            CURRENT_OPT="$1"
+            UNKNOWN_OPT=yes
+            ;;
+        esac
+        ;;
+    make)
+        case "$1" in
+        examples)
+            BUILD_EXAMPLES=yes
+            ;;
+        tests)
+            BUILD_TESTS=yes
+            ;;
+        *)
+            CURRENT_OPT="$1"
+            UNKNOWN_OPT=yes
+            ;;
+        esac
+        shift
+        ;;
+    config)
+        QMAKE_CONFIG="$QMAKE_CONFIG $1"
+        shift
+        ;;
+    # autodetection overrides
+    meegotouch)
+        if [ "$VAL" = "yes" ] || [ "$VAL" = "no" ]; then
+            HAVE_MEEGOTOUCH=$VAL
+        else
+            UNKNOWN_OPT=yes
+        fi
+        ;;
+    contextsubscriber)
+        if [ "$VAL" = "yes" ] || [ "$VAL" = "no" ]; then
+            HAVE_CONTEXTSUBSCRIBER=$VAL
+        else
+            UNKNOWN_OPT=yes
+        fi
+        ;;
+    meegographicssystem)
+        if [ "$VAL" = "yes" ] || [ "$VAL" = "no" ]; then
+            HAVE_MEEGOGRAPHICSSYSTEM=$VAL
+        else
+            UNKNOWN_OPT=yes
+        fi
+        ;;
+    xdamage)
+        if [ "$VAL" = "yes" ] || [ "$VAL" = "no" ]; then
+            HAVE_XDAMAGE=$VAL
+        else
+            UNKNOWN_OPT=yes
+        fi
+        ;;
+    *)
+        UNKNOWN_OPT=yes
+        ;;
+    esac
+    if [ "$UNKNOWN_OPT" = "yes" ]; then
+        echo "${CURRENT_OPT}: unknown option"
+        OPT_HELP=yes
+        ERROR=yes
+    fi
+done
+
+if [ "$OPT_HELP" = "yes" ]; then
+    cat << EOF
+Usage:  configure [-meego] [-symbian] [-config <config>]
+    [-make <part>] [-nomake <part>] [-help]
+
+Configure options:
+
+    -meego ................... Build MeeGo Style
+    -symbian ................. Build Symbian Style
+    -config (config) ......... Configuration options recognized by qmake
+    -make (part) ............. Add part to the list of parts to be built at
+                               make time (available parts: examples tests)
+    -nomake (part) ........... Exclude part from the list of parts to be built
+
+Additional options:
+
+ A plus (+) denotes a default value that needs to be evaluated. If the
+ evaluation succeeds, the feature is included. Here is a short explanation
+ of each option:
+
+    -no-meegotouch ........... Do not compile MeeGo Touch framework support
+ +  -meegotouch .............. Compile MeeGo Touch framework support
+
+    -no-contextsubscriber .... Do not compile Context Subscriber support
+ +  -contextsubscriber ....... Compile Context Subscriber support
+
+    -no-xdamage .............. Do not compile XDamage support
+ +  -xdamage ................. Compile XDamage support
+
+    -no-meegographicssystem .. Do not compile MeeGo graphics system support
+    -meegographicssystem ..... Compile MeeGo graphics system support
+
+EOF
+    [ "x$ERROR" = "xyes" ] && exit 1
+    exit 0
+fi
+
+[ "$BUILD_MEEGO_STYLE" = "yes" ] && QMAKE_CONFIG="$QMAKE_CONFIG meego"
+[ "$BUILD_SYMBIAN_STYLE" = "yes" ] && QMAKE_CONFIG="$QMAKE_CONFIG symbian3"
+[ "$BUILD_MX_STYLE" = "yes" ] && QMAKE_CONFIG="$QMAKE_CONFIG mx"
+[ "$BUILD_EXAMPLES" = "yes" ] && QMAKE_CONFIG="$QMAKE_CONFIG examples"
+[ "$BUILD_TESTS" = "yes" ] && QMAKE_CONFIG="$QMAKE_CONFIG tests"
+
+[ "$HAVE_MEEGOTOUCH" = "yes" ] && QMAKE_CONFIG="$QMAKE_CONFIG meegotouch"
+[ "$HAVE_CONTEXTSUBSCRIBER" = "yes" ] && QMAKE_CONFIG="$QMAKE_CONFIG contextsubscriber"
+[ "$HAVE_MEEGOGRAPHICSSYSTEM" = "yes" ] && QMAKE_CONFIG="$QMAKE_CONFIG meegographicssystem"
+[ "$HAVE_XDAMAGE" = "yes" ] && QMAKE_CONFIG="$QMAKE_CONFIG xdamage"
+
 echo "Q_COMPONENTS_SOURCE_TREE = $SOURCE_TREE" > $QMAKE_CACHE
 echo "Q_COMPONENTS_BUILD_TREE = $BUILD_TREE" >> $QMAKE_CACHE
 
 echo
-echo Running qmake...
-$QMAKE -r "$@" $SOURCE_TREE/qt-components.pro 2> /dev/null
+echo "Running qmake..."
+
+$QMAKE -r "CONFIG+=$QMAKE_CONFIG" $SOURCE_TREE/qt-components.pro
 if [ $? != 0 ]; then
-    echo "ERROR: Unable to detect qmake. Run QTDIR=/path/to/qt $0."
+    echo "ERROR: qmake run failed."
     exit 1
 fi
+
+echo
+echo
+echo "Qt Components build configuration:"
+echo "Configuration ....................$QMAKE_CONFIG"
+echo "MeeGo Style ...................... $BUILD_MEEGO_STYLE"
+if [ "$BUILD_MEEGO_STYLE" = "yes" ]; then
+    echo "  MeeGo Touch support  ........... $HAVE_MEEGOTOUCH"
+    echo "  ContextSubscriber support  ..... $HAVE_CONTEXTSUBSCRIBER"
+    echo "  XDamage support  ............... $HAVE_XDAMAGE"
+    echo "  MeeGo Graphics System support .. $HAVE_MEEGOGRAPHICSSYSTEM"
+fi
+echo "Symbian Style .................... $BUILD_SYMBIAN_STYLE"
+echo "Mx Style ......................... $BUILD_MX_STYLE"
+echo "Examples ......................... $BUILD_EXAMPLES"
+echo "Tests ............................ $BUILD_TESTS"
+echo
+echo Qt Components is now configured for building. Just run \'make\'.
+echo
